<?php
// admin/seed_questions.php
require_once '../includes/config.php';

// Pastikan hanya admin yang bisa akses (Opsional, matikan jika belum bisa login)
// requireAdmin(); 

$db = getDB();

// ARRAY DATA 567 SOAL (Dari input Anda)
$questions = [
    "Aku suka majalah teknik",
    "Nafsu makan-ku baik",
    "Aku bangun dengan rasa nyaman hampir setiap pagi",
    "Aku mengira aku dapat menyukai pekerjaan perpustakaan",
    "Aku mudah terbangun oleh suara berisik",
    "Ayah-ku (Almarhum ayah-ku) seorang yang baik",
    "Aku senang membaca berita kejahatan di surat kabar",
    "Tangan dan kaki-ku biasanya terasa cukup hangat",
    "Kehidupan-ku sehari-hari terisi penuh dengan hal-hal yang menarik",
    "Aku sanggup bekerja sebagaimana biasanya",
    "Aku sering merasa seolah-olah ada yang menyumbat dalam tenggorokan-ku",
    "Kehidupan seks-ku cukup memuaskan",
    "Seseorang harus berusaha memahami mimpinya sebagai petunjuk atau peringatan baginya",
    "Aku senang cerita detektif atau cerita yang misterius",
    "Aku bekerja dalam ketegangan yang sangat besar",
    "Sekali-sekali aku berpikir tentang hal-hal yang buruk untuk diutarakan",
    "Aku yakin bahwa hidup ini tidak adil",
    "Aku terganggu oleh serangan rasa mual dan muntah-muntah",
    "Bila aku melamar pekerjaan baru, aku ingin tahu siapa yang penting untuk aku hubungi lebih dahulu",
    "Aku jarang sekali terganggu sembelit (kesukaran buang air besar)",
    "Aku pernah ingin sekali lari dari rumah",
    "Aku merasa tidak seorang-pun yang mengerti akan diri-ku",
    "Pada waktu-waktu tertentu aku tertawa dan menangis tanpa dapat aku kendalikan",
    "Ada kalanya aku di-masuki roh jahat",
    "Aku ingin menjadi penyanyi",
    "Aku rasa lebih baik aku tutup mulut bila dalam kesulitan",
    "Prinsip-ku adalah berusaha membalas orang yang berbuat salah kepada-ku",
    "Aku terganggu oleh penyakit lambung (maag) beberapa kali dalam seminggu",
    "Ada kalanya aku merasa ingin mengumpat (caci maki)",
    "Aku bermimpi buruk beberapa malam sekali",
    "Aku merasa sukar untuk memusatkan perhatian pada suatu pekerjaan atau tugas",
    "Aku pernah mengalami hal-hal yang aneh dan tidak masuk akal",
    "Aku jarang merisaukan kesehatan-ku",
    "Aku belum pernah mengalami kesulitan karena kelakuan seks-ku",
    "Dalam suatu masa tertentu ketika masih muda, aku pernah melakukan pencurian kecil-kecilan",
    "Aku batuk-batuk hampir setiap waktu",
    "Kadang-kadang aku ingin membanting barang-barang",
    "Aku pernah mengalami tidak dapat mengurus sesuatu selama berhari-hari, beberapa minggu, atau sampai berbulan-bulan, karena tidak dapat memulainya",
    "Tidur-ku sering terganggu dan terbangun-bangun",
    "Aku sering merasa seluruh kepala-ku sakit",
    "Aku tidak selalu mengatakan yang benar",
    "Bila orang-orang tidak menghalangi, aku akan lebih sukses lagi",
    "Sekarang aku lebih mampu mengambil sesuatu keputusan daripada dahulu",
    "Sekali atau lebih dalam seminggu, aku tiba-tiba merasa panas tanpa sesuatu sebab yang jelas",
    "Kesehatan-ku kurang lebih sama baiknya dengan kesehatan kawan-kawan-ku",
    "Bila aku berpapasan dengan teman-teman sekolah atau kenalan lama, aku lebih suka menghindari mereka, kecuali bila mereka menegur aku lebih dahulu",
    "Aku hampir tidak pernah terganggu rasa nyeri pada jantung atau dada",
    "Pada umumnya aku lebih suka duduk melamun daripada mengerjakan yang lain",
    "Aku seorang yang mudah bergaul",
    "Aku sering harus menerima perintah dari seseorang yang tidak lebih pandai dari diri-ku",
    "Aku tidak membaca setiap tajuk (judul) pada surat kabar harian",
    "Aku belum menjalani hidup yang benar",
    "Pada beberapa bagian tubuh-ku sering terasa panas, kesemutan atau seperti ada yang merayap",
    "Keluarga-ku tidak senang pada pekerjaan yang telah atau akan aku pilih untuk nafkah-ku",
    "Aku kadang-kadang tetap bertahan pada sesuatu hal sehingga orang lain menjadi tidak sabar",
    "Aku mengharapkan dapat berbahagia seperti orang lain",
    "Aku hampir tidak pernah merasa sakit di tengkuk-ku",
    "Aku kira banyak orang suka melebih-lebihkan kemalangannya untuk memperoleh simpati dan pertolongan orang lain",
    "Aku terganggu oleh rasa tidak enak pada ulu hati (lambung) setiap beberapa hari sekali atau lebih sering",
    "Pada waktu bersama orang-orang, aku merasa terganggu oleh suara-suara yang sangat aneh",
    "Aku termasuk orang yang penting",
    "(Bila pria) Aku sering ingin, seandainya aku menjadi wanita. (Bila wanita) Aku tidak pernah menyesal sebagai wanita",
    "Perasaan-ku tidak mudah tersinggung",
    "Aku senang membaca kisah cinta",
    "Aku sering sekali merasa murung",
    "Rasanya akan lebih baik, apabila semua Undang-Undang ditiadakan",
    "Aku menyukai sajak dan puisi",
    "Aku kadang-kadang mempermainkan binatang",
    "Aku senang juga dengan pekerjaan sebagai polisi atau penjaga hutan",
    "Aku mudah dikalahkan dalam perdebatan",
    "Akhir-akhir ini aku sukar melawan perasaan hilangnya harapan untuk menjadi orang yang berhasil",
    "Roh-ku kadang-kadang meninggalkan tubuh-ku",
    "Aku memang kurang kepercayaan pada diri-ku sendiri",
    "Aku ingin menjadi pedagang bunga (florist)",
    "Pada umumnya aku merasa bahwa hidup ini ada manfaatnya",
    "Untuk meyakinkan orang tentang kebenaran dibutuhkan banyak pembicaraan dan pembahasan",
    "Apa yang harus aku kerjakan hari ini, kadang-kadang aku tunda sampai besok",
    "Aku disukai oleh kebanyakan orang yang mengenal aku",
    "Aku tahan dijadikan bahan lelucon",
    "Aku ingin menjadi juru rawat (nurse)",
    "Menurut pendapat-ku, sebagian besar orang akan berbohong untuk memperoleh kemajuan",
    "Aku banyak melakukan hal-hal yang kemudian aku sesalkan (Rasanya aku lebih sering menyesal daripada orang lain)",
    "Aku sedikit sekali bertengkar dengan anggota keluarga-ku",
    "Aku pernah dikeluarkan dari sekolah oleh karena bandel atau nakal",
    "Ada kalanya aku terdorong dengan kuat untuk melakukan sesuatu yang berbahaya atau mengejutkan",
    "Aku senang pergi ke pesta dan hal-hal lain yang sangat menggembirakan",
    "Aku pernah dihadapkan pada persoalan yang begitu banyak kemungkinannya, sehingga aku tidak dapat mengambil keputusan",
    "Aku berpendapat bahwa perempuan seharusnya mendapat kebebasan seks yang setaraf dengan laki-laki",
    "Peperangan-ku yang paling berat adalah melawan diri sendiri",
    "Aku sayang pada Ayah-ku (almarhum Ayah-ku)",
    "Aku tidak terganggu oleh kejutan-kejutan otot (kedutan)",
    "Rasanya aku tidak peduli dengan apa yang terjadi pada diri-ku",
    "Bila aku sedang tidak enak badan, kadang-kadang aku mudah marah",
    "Aku sering merasa seakan-akan telah melakukan sesuatu yang salah atau jahat",
    "Pada umumnya aku cukup bahagia",
    "Aku melihat ada makhluk atau benda di sekitar-ku, yang tidak tampak oleh orang lain",
    "Kepala-ku sering sekali terasa berat atau hidung-ku mampet",
    "Ada orang yang sok tuan besar, sehingga walaupun aku tahu ia benar, aku rasanya ingin melakukan yang sebaliknya dari permintaannya",
    "Seseorang telah memojokkan aku, sehingga aku tidak berkutik",
    "Aku tidak pernah melakukan sesuatu yang berbahaya hanya untuk kesenangan saja",
    "Aku sering merasa seakan-akan ada ikatan yang menjepit kepala-ku",
    "Aku kadang-kadang marah",
    "Aku lebih menyukai suatu pertandingan yang disertai taruhan",
    "Kebanyakan orang berbuat jujur terutama karena takut ditangkap",
    "Di sekolah dahulu aku kadang-kadang dipanggil kepala sekolah karena terlalu bandel atau nakal",
    "Bicara-ku lancar dan jelas seperti biasanya (tidak cepat atau lambat, pelo atau serak-serak)",
    "Tata cara makan-ku di rumah tidak sebaik seperti jika bersama orang lain",
    "Setiap orang yang mampu dan mau bekerja keras mempunyai kesempatan untuk sukses",
    "Rasanya aku sama mampu dan pandainya seperti orang lain di sekitar-ku",
    "Banyak orang akan menggunakan cara-cara yang agak kurang jujur untuk memperoleh keuntungan, daripada kehilangan keuntungan tersebut",
    "Aku sering menderita sakit perut",
    "Aku menyukai seni drama",
    "Aku tahu siapa yang menjadi biang keladi dari kesulitan-kesulitan-ku",
    "Kadang-kadang aku begitu tertarik pada barang-barang pribadi orang lain (seperti sepatu, pakaian, dll) sehingga aku ingin memegang atau mencurinya, walaupun aku tidak mempergunakannya",
    "Aku tidak takut atau tidak terganggu ketika melihat darah",
    "Kadang-kadang aku tidak mengerti mengapa aku marah dan mengomel",
    "Aku belum pernah batuk darah atau muntah darah",
    "Aku tidak khawatir terserang penyakit",
    "Aku suka mengumpulkan dan memelihara tanaman hias atau bunga",
    "Aku sering merasa perlu mempertahankan dengan gigih apa yang aku anggap benar",
    "Aku belum pernah tertarik dan melakukan perbuatan seks yang tidak wajar",
    "Ada kalanya pikiran-ku lebih cepat dari ucapan-ku",
    "Bila aku yakin tidak seorang-pun yang melihatnya, mungkin sekali aku akan menyelundup nonton tanpa karcis",
    "Apabila ada orang yang berbuat sangat baik terhadap-ku, aku biasanya bertanya-tanya tentang alasan tersembunyinya",
    "Aku berpendapat bahwa kehidupan keluarga-ku sama menyenangkannya dengan kebanyakan keluarga yang aku kenal",
    "Aku percaya pada penegakan hukum",
    "Kritik dan teguran sangat menyakitkan hati-ku",
    "Aku senang memasak",
    "Kelakuan-ku banyak dipengaruhi oleh perilaku orang-orang di lingkungan-ku",
    "Kadang-kadang aku benar-benar merasa tidak berguna",
    "Semasa muda, aku menjadi anggota kelompok yang kompak dalam suka dan duka",
    "Aku percaya adanya kehidupan setelah kematian",
    "Aku ingin menjadi tentara",
    "Ada kalanya aku merasa ingin berkelahi dengan seseorang",
    "Aku sering kehilangan kesempatan baik, karena tidak mampu membuat keputusan yang cepat",
    "Bila aku sedang sibuk dengan sesuatu yang penting, orang datang minta nasehat dan mengganggu waktu-ku, aku menjadi tidak sabar",
    "Aku biasanya menulis pengalaman-ku dalam buku harian",
    "Aku yakin bahwa ada komplotan yang memusuhi aku",
    "Aku lebih ingin menang dari pada kalah dalam suatu permainan",
    "Biasanya aku pergi tidur malam tanpa pikiran yang mengganggu",
    "Beberapa tahun terakhir ini, pada umumnya aku sehat-sehat aja",
    "Aku tidak pernah sakit ayan atau kejang-kejang",
    "Berat badan-ku tetap saja, tidak naik maupun tidak turun",
    "Aku yakin aku sedang diikuti (dikuntit)",
    "Aku merasa bahwa aku sering dihukum tanpa sebab",
    "Aku mudah menangis",
    "Bila membaca, daya tangkap-ku tidak lagi sebaik dulu",
    "Aku tidak pernah merasa sesenang seperti sekarang ini",
    "Ubun-ubun kepala-ku kadang-kadang terasa nyeri bila diraba",
    "Kadang-kadang aku merasa seakan-akan aku harus melukai diri-ku sendiri atau orang lain",
    "Aku mendongkol bila orang dengan cerdik menipu-ku, sehingga aku harus mengakui kebodohan-ku",
    "Aku tidak cepat lelah",
    "Aku ingin mengenal orang-orang penting, karena dengan demikian aku merasa menjadi orang penting juga",
    "Bila melihat ke bawah dari tempat yang tinggi, aku menjadi takut",
    "Aku tidak akan gelisah bila salah seorang anggota keluarga-ku terlibat dalam perkara hukum",
    "Aku berjiwa pengembara dan tidak merasa bahagia bila tidak berkelana",
    "Aku tidak terganggu oleh apa yang orang pikirkan tentang diri-ku",
    "Aku merasa canggung berbuat sesuatu yang menonjolkan diri dalam pesta, walaupun orang lain melakukannya",
    "Aku belum pernah mengalami serangan pingsan",
    "Pada waktu yang lalu, aku senang bisa bersekolah",
    "Aku sering harus berusaha keras untuk menyembunyikan rasa malu",
    "Seseorang telah mencoba meracuni aku",
    "Aku tidak terlampau takut pada ular",
    "Aku jarang atau tidak pernah diserang pusing (tujuh keliling)",
    "Daya ingat-ku baik-baik saja",
    "Aku merisaukan masalah seks",
    "Aku sulit memulai percakapan bila bertemu dengan orang yang baru aku kenal",
    "Ada kalanya aku melakukan sesuatu, yang kemudian tidak diketahui bahwa akulah yang melakukannya",
    "Bila aku menjadi bosan, aku suka membuat hal-hal yang menggairahkan",
    "Aku takut hilang kesadaran diri-ku",
    "Aku tidak setuju memberi uang kepada pengemis",
    "Aku sering menemukan, tangan-ku gemetar bila aku mencoba melakukan sesuatu",
    "Aku mampu membaca lama tanpa melelahkan mata-ku",
    "Aku suka mempelajari dan membaca tentang apa yang sedang aku kerjakan",
    "Aku sering merasa seluruh badan-ku lemah",
    "Aku jarang sekali sakit kepala",
    "Tangan-ku belum pernah mengalami hilang keterampilan atau kelincahan",
    "Kadang-kadang, bila malu dan canggung, aku mandi keringat yang sangat mengganggu",
    "Aku mudah saja menjaga keseimbangan badan-ku sewaktu berjalan",
    "Ada sesuatu yang tidak beres dengan pikiran-ku",
    "Aku tidak menderita serangan selesma atau sesak napas",
    "Aku pernah mengalami serangan tidak mampu mengendalikan pergerakan badan-ku dan pembicaraan-ku, walaupun aku sadar apa yang terjadi di sekitar-ku",
    "Aku tidak selalu menyukai setiap orang yang aku kenal",
    "Aku jarang sekali melamun",
    "Aku ingin tidak pemalu seperti ini",
    "Aku tidak takut mengurus uang",
    "Andai kata aku seorang wartawan, aku akan senang sekali memberitakan tentang seni drama",
    "Aku menikmati bermacam-macam pertunjukan dan hiburan",
    "Aku suka bercumbu rayu",
    "Keluarga-ku lebih memperlakukan aku sebagai kanak-kanak dari pada sebagai orang dewasa",
    "Aku ingin juga menjadi wartawan",
    "Ibu-ku (Almarhumah Ibu-ku) seorang yang baik",
    "Sewaktu berjalan aku sangat berhati-hati agar tidak salah injak",
    "Aku tidak pernah cemas dengan kelainan pada kulit-ku yang mendadak muncul",
    "Dibandingkan dengan keluarga lain, kasih sayang dan keakraban dalam keluarga-ku sangat kurang",
    "Ternyata aku sering merisaukan sesuatu",
    "Aku senang pekerjaan seorang pemborong bangunan",
    "Aku sering mendengar suara-suara yang tidak aku ketahui dari mana asalnya",
    "Aku suka pada ilmu pengetahuan",
    "Mudah bagi-ku untuk minta pertolongan dari kawan-kawan-ku, walaupun aku tidak sanggup membalasnya",
    "Aku gemar sekali berburu binatang",
    "Orang tua-ku sering tidak setuju terhadap teman-teman yang aku pilih",
    "Ada kalanya aku mempergunjingkan orang lain (gossip)",
    "Pendengaran-ku ternyata sama baik-nya dengan orang lain",
    "Beberapa anggota keluarga-ku mempunyai kebiasaan yang sangat mengganggu dan menjengkelkan aku",
    "Ada kalanya aku merasa mudah sekali membuat keputusan",
    "Aku ingin juga menjadi anggota dari beberapa perkumpulan",
    "Aku hampir tidak pernah memperhatikan jantung-ku berdebar dan aku jarang sesak napas",
    "Aku suka membicarakan perihal seks",
    "Aku suka mengunjungi tempat yang belum pernah aku kunjungi",
    "Aku terpanggil untuk mengisi hidupku dengan tugas yang mulia, yang selama ini telah aku laksanakan dengan sungguh-sungguh",
    "Kadang-kadang aku menghalangi orang yang mencoba berbuat sesuatu, bukan karena besar kecil-nya persoalan, akan tetapi karena prinsip",
    "Aku mudah menjadi marah dan kemudian cepat reda kembali",
    "Aku cukup bebas dan tidak terikat pada peraturan-peraturan keluarga",
    "Aku sering sekali murung dan bengong",
    "Seseorang telah mencoba merampas barang-barang-ku",
    "Hampir semua sanak keluarga-ku bersimpati pada aku",
    "Pada saat-saat tertentu aku merasa gelisah sekali, sehingga tidak dapat duduk dengan tenang",
    "Aku telah dikecewakan dalam cinta",
    "Aku tidak pernah khawatir akan penampilan-ku (cara berpakaian dan berhias)",
    "Aku sering bermimpi tentang hal-hal yang lebih baik aku ketahui sendiri saja",
    "Anak-anak seharusnya diberi pelajaran tentang fakta-fakta dalam seks",
    "Aku yakin aku tidak lebih gugup dari orang lain",
    "Aku tidak atau sedikit mengalami rasa nyeri atau sakit-sakit",
    "Cara-ku melakukan sesuatu biasanya disalah-tafsirkan oleh orang lain",
    "Kadang-kadang tanpa alasan atau meskipun segala sesuatunya tidak sesuai, aku toh merasa sangat gembira sekali",
    "Aku tidak menyalahkan orang-orang yang mencoba meraih apa saja sebanyak-banyaknya di dunia ini",
    "Ada orang-orang yang mencoba mencuri ide dan buah pikiran-ku",
    "Aku pernah mengalami pikiran-ku mendadak kosong, serta kegiatan-ku terhenti, dan aku tidak tahu lagi apa yang terjadi disekitar-ku",
    "Aku mampu bersikap tetap ramah terhadap orang-orang yang melakukan hal-hal yang menurut hemat-ku salah",
    "Aku suka berkumpul dengan orang-orang yang suka bercanda atau bergurau",
    "Aku kadang-kadang memilih orang-orang yang tidak begitu aku kenal dalam suatu pemilihan",
    "Aku merasa berat untuk memulai suatu pekerjaan",
    "Aku percaya bahwa aku seorang yang terkutuk",
    "Dahulu ketika sekolah, aku lambat menangkap pelajaran",
    "Andaikata aku pelukis, aku akan senang melukis bunga",
    "Aku tidak peduli akan diri-ku yang kurang tampan atau cantik",
    "Aku mudah sekali berkeringat walaupun dalam udara dingin",
    "Aku sepenuhnya percaya pada diri sendiri",
    "Ada kalanya tidak mungkin bagi-ku untuk menahan diri dari keinginan mencuri atau mencopet",
    "Lebih aman untuk tidak mempercayai siapa-pun",
    "Sekali seminggu atau lebih, aku menjadi sangat bersemangat dan bergairah",
    "Ketika dalam pertemuan kelompok, aku mengalami kesukaran menemukan bahan pembicaraan",
    "Sesuatu yang menggairahkan hampir selalu akan menghilangkan kesedihan-ku",
    "Jika aku pergi, aku tidak merisaukan apakah pintu atau jendela sudah terkunci atau belum",
    "Aku percaya dosa-ku tidak dapat diampuni",
    "Kulit-ku terasa kebal (baal) pada beberapa tempat",
    "Aku tidak menyalahkan seorang yang akan mengambil keuntungan dari orang-orang yang lengah",
    "Penglihatan-ku sekarang sama baiknya dengan penglihatan-ku pada tahun-tahun yang lalu",
    "Ada kalanya aku begitu kagum akan ke-lihai-an (kepiawaian) seorang bajingan, sehingga aku mengharap dia dapat lolos",
    "Aku sering merasa orang-orang yang tidak aku kenal, memperhatikan aku secara teliti",
    "Semua rasanya sama saja",
    "Setiap hari aku minum air dalam jumlah yang luar biasa banyaknya",
    "Kebanyakan orang mencari kawan, karena diharapkan akan berguna bagi dirinya",
    "Aku jarang memperhatikan suara mendengung (berisik) dalam telinga-ku",
    "Sekali waktu aku merasa benci terhadap anggota keluarga-ku yang biasanya aku sayangi",
    "Seandainya aku wartawan, aku ingin sekali menulis berita olah raga",
    "Pada siang hari aku dapat tidur, tetapi pada malam hari tidak",
    "Aku yakin bahwa aku dipergunjingkan (digosipkan) orang",
    "Sekali-sekali aku tertawa juga mendengar lelucon porno",
    "Dibandingkan dengan kawan-kawan-ku, aku sedikit sekali mempunyai rasa takut",
    "Dalam pertemuan kelompok, aku tidak akan malu-malu bila diminta untuk memulai diskusi, atau memberikan pendapat tentang sesuatu yang aku ketahui",
    "Aku selalu merasa muak terhadap hukum, ketika seorang penjahat dibebaskan hanya oleh karena kepandaian dari pembelanya",
    "Aku minum minuman keras (alkohol) berlebihan",
    "Aku cenderung untuk tidak menyapa orang lain, sebelum mereka menyapa aku lebih dahulu",
    "Aku belum pernah mengalami kesulitan dengan hukum",
    "Pada waktu-waktu tertentu aku merasa gembira sekali tanpa alasan yang jelas",
    "Aku ingin tidak terganggu oleh pikiran-pikiran tentang seks",
    "Bila beberapa orang bersama-sama dalam kesulitan, hal yang terbaik mereka lakukan adalah menyetujui kesepakatan dan berpedoman kepadanya",
    "Aku merasa tidak terganggu melihat binatang yang menderita",
    "Aku kira perasaan-ku lebih mendalam dari orang lain",
    "Selama hidup-ku ini aku tidak pernah senang bermain-main dengan boneka",
    "Pada umumnya dalam hidup ini, aku rasakan berat",
    "Aku sangat peka terhadap beberapa persoalan, sehingga aku tidak dapat membicarakannya",
    "Sewaktu sekolah, aku merasa sukar untuk bicara di depan kelas",
    "Aku sayang pada Ibu-ku (almarhumah Ibu-ku)",
    "Walaupun bersama-sama dengan orang banyak, aku sering merasa kesepian",
    "Aku mendapat simpati (dukungan) yang sudah semestinya",
    "Aku menolak ikut serta dalam beberapa permainan karena aku kurang pandai dalam permainan tersebut",
    "Aku merasa dapat berkawan semudah orang lain",
    "Aku tidak suka ada orang-orang di sekitar-ku",
    "Menurut orang, aku berjalan-jalan sewaktu tidur",
    "Orang yang memberikan peluang mencuri dengan meninggalkan barang berharga begitu saja, sama salahnya dengan orang yang mencurinya",
    "Menurut pendapat-ku, hampir setiap orang akan berbohong untuk menghindarkan kesulitan",
    "Aku lebih perasa (sensitif) dari kebanyakan orang",
    "Kebanyakan orang dalam hati kecilnya tidak begitu suka mengulurkan tangan untuk menolong orang lain",
    "Kebanyakan mimpi-ku adalah tentang seks",
    "Orang tua dan keluarga-ku sering menyalahkan aku",
    "Aku mudah sekali menjadi canggung dan malu-malu",
    "Aku merisaukan soal uang dan pekerjaan",
    "Aku belum pernah jatuh cinta pada siapa pun juga",
    "Beberapa hal yang telah dilakukan oleh anggota keluarga-ku, menakutkan aku",
    "Aku hampir tidak pernah bermimpi",
    "Leher-ku sering membercak merah",
    "Aku tidak pernah lumpuh atau mengalami kelemahan otot yang berat",
    "Kadang-kadang suara-ku menghilang atau berubah, walaupun aku tidak sakit tenggorokan (flu)",
    "Orang tua-ku sering membuat aku menuruti kehendaknya, walaupun menurut pendapat-ku hal itu tidak beralasan",
    "Ada kalanya tercium oleh-ku bau yang aneh",
    "Aku tidak dapat memusatkan pikiran-ku pada satu hal saja",
    "Aku ada alasan untuk merasa iri hati terhadap satu atau beberapa anggota keluarga-ku",
    "Aku hampir selalu merasa cemas terhadap sesuatu hal atau seseorang",
    "Aku mudah menjadi kurang sabar terhadap orang-orang",
    "Sering sekali aku ingin mengalami mati",
    "Kadang-kadang aku begitu sangat bersemangat dan bergairah, sehingga sukar tidur",
    "Sesungguhnya lebih banyak persoalan yang aku risaukan dari pada yang seharusnya",
    "Tiada seorang-pun yang banyak peduli terhadap apa yang terjadi pada diri-ku",
    "Ada kalanya pendengaran-ku sedemikian tajamnya, sehingga aku merasa terganggu",
    "Aku cepat sekali lupa tentang apa yang dikatakan orang pada-ku",
    "Biasanya aku harus berpikir-pikir dahulu sebelum melakukan sesuatu, walaupun mengenai hal yang sepele (kecil dan tidak berarti)",
    "Aku sering menghindar bertemu seseorang dengan merubah arah langkah-ku",
    "Aku sering merasa seakan-akan semuanya semu (tidak nyata)",
    "Satu-satunya bagian yang menarik dari surat kabar adalah ruang komik yang lucu",
    "Aku mempunyai kebiasaan menghitung benda-benda yang tidak perlu dihitung, seperti tiang-tiang listrik, kancing baju, dan lain-lain",
    "Aku tidak mempunyai musuh yang benar-benar bermaksud mencelakakan aku",
    "Aku cenderung untuk waspada terhadap orang yang agak berlebihan ramahnya",
    "Aku merasa pikiran-ku aneh dan asing",
    "Aku menjadi cemas dan gelisah bila aku harus bepergian",
    "Aku biasanya mengharapkan usaha-ku akan berhasil",
    "Bila aku seorang diri, aku mendengar suara-suara yang aneh",
    "Aku takut pada benda atau orang yang aku ketahui tidak akan membahayakan diri-ku",
    "Aku tidak takut masuk sendirian ke dalam suatu ruangan yang di dalamnya berkumpul orang-orang yang sedang berbicara",
    "Aku takut menggunakan pisau atau benda yang tajam lainnya",
    "Kadang-kadang aku senang menyakiti orang yang aku sayangi",
    "Aku dengan mudah dapat membuat orang-orang takut pada-ku, dan kadang-kadang ini aku lakukan untuk iseng",
    "Aku merasa lebih sukar memusatkan perhatian dari pada orang lain",
    "Aku telah beberapa kali meninggalkan suatu pekerjaan karena aku merasa kurang mampu",
    "Kata-kata busuk, seringkali kata-kata mengerikan, muncul dalam pikiran-ku dan aku tidak dapat menghilangkannya",
    "Kadang-kadang, beberapa pikiran yang tidak penting memenuhi benak-ku dan mengganggu aku selama beberapa hari",
    "Hampir setiap hari ada saja kejadian yang menakutkan aku",
    "Kadang-kadang aku penuh semangat dan tenaga",
    "Aku cenderung menganggap segala sesuatunya sulit dan sukar",
    "Ada kalanya aku senang disakiti oleh orang yang aku cintai",
    "Orang-orang mengatakan hal-hal yang menghina dan kasar tentang diri-ku",
    "Aku merasa tidak betah di dalam rumah",
    "Aku biasanya sadar tentang diri sendiri",
    "Seseorang telah mengendalikan pikiran-ku",
    "Dalam pesta, aku lebih suka duduk sendirian atau hanya dengan seorang lain, dari pada menggabungkan diri dalam kelompok",
    "Orang-orang sering mengecewakan aku",
    "Kadang-kadang aku merasa bahwa kesulitan-ku begitu bertumpuk-tumpuk, sehingga aku tidak mampu mengatasinya",
    "Aku senang pergi ke pesta dansa",
    "Pada waktu-waktu tertentu, pikiran-ku bekerja lebih lambat dari biasanya",
    "Ketika dalam kereta api, bus, dan lain-lain, aku sering bercakap-cakap dengan orang yang tidak aku kenal sebelumnya",
    "Aku senang bersama anak-anak",
    "Aku menyenangi bermain judi kecil-kecilan",
    "Bila aku diberi kesempatan, aku dapat berbuat sesuatu yang bermanfaat besar bagi masyarakat",
    "Aku sering menjumpai orang-orang yang dianggap ahli, yang ternyata tidak lebih unggul dari aku",
    "Aku merasa seperti orang yang gagal, bila mendengar keberhasilan seseorang yang aku kenal baik",
    "Aku sering berangan-angan menjadi anak-anak kembali",
    "Aku tidak pernah lebih bahagia dari pada ketika aku sendirian",
    "Apabila aku diberi kesempatan, aku bisa menjadi pemimpin yang baik",
    "Aku merasa malu mendengar cerita jorok (porno)",
    "Pada umumnya orang menuntut penghargaan yang lebih baik bagi hak-hak mereka, daripada mereka mau menghargai hak-hak orang lain",
    "Aku senang menghadiri pertemuan sosial hanya untuk kebersamaan",
    "Aku berusaha mengingat-ingat cerita yang baik untuk disampaikan kepada orang lain",
    "Aku pernah beberapa kali merasa bahwa seseorang memaksa aku melakukan sesuatu dengan sihir atau hipnotis",
    "Sukar bagi-ku meninggalkan suatu tugas, walaupun hanya untuk sementara waktu saja",
    "Aku sering sekali tidak terlibat dalam gosip dan hanya membicarakan hal-hal tentang kelompok-ku",
    "Aku sering menemukan bahwa orang-orang iri hati pada ide-ide baik-ku, hanya karena mereka tidak menemukannya lebih dahulu",
    "Aku menyenangi kegembiraan dalam suatu keramaian",
    "Aku tidak berkeberatan menghadapi orang yang tidak aku kenal",
    "Seseorang telah mencoba mempengaruhi pikiran-ku",
    "Aku ingat pernah \"pura-pura sakit\" untuk menghindari sesuatu",
    "Kerisauan-ku seakan-akan menghilang ketika aku berkumpul dengan kawan-kawan yang bergembira",
    "Aku merasa cepat menyerah bila keadaan memburuk",
    "Aku suka memberi tahu kepada orang-orang tentang pendirian-ku",
    "Ada kalanya aku merasa begitu bersemangat dan bergairah, sehingga aku tidak perlu tidur berhari-hari",
    "Sedapat mungkin, aku menghindar berada di keramaian",
    "Aku menarik diri dalam menghadapi krisis atau kesulitan",
    "Aku biasanya melakukan apa yang ingin aku lakukan, walaupun orang lain merasa itu tidak pantas dilakukan",
    "Aku senang pesta dan kumpul-kumpul",
    "Aku sering mengharapkan menjadi jenis kelamin yang berbeda dengan yang ada sekarang",
    "Aku tidak mudah dibuat marah",
    "Aku telah melakukan beberapa hal yang buruk pada masa lalu, yang tidak pernah aku ceritakan kepada siapapun",
    "Kebanyakan orang menggunakan cara-cara yang tidak baik untuk bertahan hidup",
    "Bila orang menanyakan soal-soal pribadi, aku menjadi risau",
    "Aku tidak merasa aku mampu merencanakan masa depan-ku",
    "Aku tidak bahagia dengan keadaan diri-ku sendiri",
    "Aku menjadi marah bila teman-ku atau keluarga-ku menasehati aku tentang bagaimana menjalankan hidup-ku",
    "Aku sering dipukuli sewaktu masih anak-anak",
    "Aku merasa terganggu, bila orang-orang mengatakan hal-hal yang baik saja tentang diri-ku",
    "Aku tidak suka mendengarkan pendapat orang lain tentang hidup-ku",
    "Aku sering tidak sepaham dengan orang-orang yang dekat dengan aku",
    "Bila keadaan menjadi buruk sekali, aku dapat mengandalkan keluarga-ku untuk memperoleh bantuan",
    "Aku suka bermain \"rumah-rumahan\" ketika masih kanak-kanak",
    "Aku tidak takut pada api",
    "Aku kadang-kadang menjauhi orang lain, oleh karena aku khawatir melakukan atau berkata sesuatu yang aku sesalkan dikemudian hari",
    "Aku dapat mengungkapkan perasaan-ku yang sebenarnya hanya bila aku minum minuman keras (alkohol)",
    "Aku jarang sekali diserang perasaan murung",
    "Aku sering dikatakan berkepala panas (mudah marah)",
    "Aku harap aku mampu mengatasi perasaan khawatir terhadap kata-kata-ku yang melukai perasaan orang lain",
    "Aku merasa tidak mampu memberi tahu siapa-pun tentang diri-ku",
    "Salah satu yang aku takutkan adalah Kilat",
    "Aku suka membuat orang menebak-nebak apa yang akan aku lakukan berikutnya",
    "Rencana-ku sering tampak penuh dengan kesulitan, yang membuat aku harus menyerah",
    "Aku takut sendirian di dalam kegelapan",
    "Aku sering merasa takut salah paham bila mencoba membantu seseorang agar tidak membuat kesalahan",
    "Angin badai menakutkan aku",
    "Aku sering meminta nasehat kepada orang-orang",
    "Masa depan adalah penuh dengan ketidak-pastian untuk seseorang yang sedang membuat rencana yang serius",
    "Aku sering merasa tidak peduli (cuek), walaupun semuanya berjalan dengan baik",
    "Aku tidak takut dengan air",
    "Aku sering harus berpikir berhari-hari sebelum memutuskan apa yang mesti dilakukan",
    "Orang-orang sering salah paham terhadap itikad baik-ku, ketika aku mencoba membantu mereka",
    "Aku tidak ada gangguan menelan",
    "Aku biasanya tenang dan tidak mudah menjadi gelisah",
    "Aku akan merasa senang sekali bila dapat mengalahkan para penjahat dengan cara-cara mereka",
    "Aku patut dihukum berat untuk dosa-dosa-ku",
    "Aku mudah mengalami kekecewaan yang begitu mendalam, sehingga aku tidak dapat melupakannya",
    "Walaupun aku tahu bahwa aku mampu menyelesaikan suatu pekerjaan dengan baik, aku tetap merasa terganggu bila seseorang mengamati aku sewaktu bekerja",
    "Aku sering merasa begitu jengkel bila seseorang mencoba menyalip aku sewaktu antri, sehingga aku perlu menegurnya",
    "Ada kalanya aku merasa tidak berguna sama sekali",
    "Semasa muda aku sering membolos sekolah",
    "Satu atau lebih dari anggota keluarga-ku sangat mudah gugup",
    "Ada kalanya aku harus bersikap kasar terhadap orang-orang yang tidak sopan atau menjengkelkan",
    "Aku banyak risau tentang kemalangan-kemalangan yang mungkin terjadi",
    "Aku mempunyai pendirian politik yang kokoh",
    "Aku ingin menjadi pembalap mobil",
    "Seseorang boleh saja menolak hukum, asal tidak melanggarnya",
    "Ada orang tertentu yang sangat tidak aku sukai, yaitu orang yang menyenangkan aku bila mereka telah berhasil melakukan sesuatu",
    "Aku merasa gelisah bila harus menunggu",
    "Aku mudah menangguhkan sesuatu yang akan aku lakukan, karena orang lain menganggap aku tidak melakukannya dengan benar",
    "Ketika masih muda, aku menyukai hal-hal yang mendebarkan",
    "Aku sering cenderung beralih dari pendapat-ku untuk memperoleh kesepakatan dari seseorang yang menentang-ku",
    "Aku terganggu oleh orang-orang (di luar, di jalanan, di toko dan lain-lain) yang mengamati aku",
    "Orang yang mengasuh aku ketika masih anak-anak, sangat ketat mengawasi aku",
    "Dulu aku suka bermain petak umpat dan lompat tali (permainan anak)",
    "Aku tidak pernah melihat sesuatu penampakan (penglihatan gaib)",
    "Aku beberapa kali mengubah pandangan tentang karya-karya hidup-ku",
    "Aku tidak pernah minum obat-obatan apapun, kecuali atas perintah dokter",
    "Aku sering menyesal karena aku mudah marah dan resah",
    "Di waktu sekolah, angka-angka-ku mengenai perilaku biasanya buruk",
    "Aku terpesona melihat api",
    "Bila aku disudutkan, aku akan menceritakan bagian-bagian dari kebenaran yang tidak merugikan aku",
    "Andaikata aku dan beberapa kawan-kawanku mendapat kesulitan karena sama-sama bersalah, aku akan memikul seluruh tanggung jawab itu sendiri",
    "Aku sering takut pada gelap",
    "Bila seorang laki-laki berada bersama seorang wanita, biasanya ia akan berpikir mengenai hal-hal yang berkaitan dengan seks wanita itu",
    "Aku biasanya berkata langsung kepada orang-orang yang ingin aku koreksi atau perbaiki kesalahannya",
    "Aku khawatir sekali akan terjadi gempa bumi",
    "Aku siap menjadi pendukung sepenuhnya dari pendapat-pendapat yang baik",
    "Aku biasanya mencari jalan keluar sendiri dari pada minta tolong orang lain",
    "Aku takut bila berada di kamar kecil (toilet) atau di ruangan sempit tertutup",
    "Aku harus mengakui bahwa aku kadang-kadang terlalu merisaukan sesuatu yang sebenarnya tidak perlu dirisaukan",
    "Aku tidak berusaha mengungkapkan pendapat-ku yang jelek terhadap seseorang, sehingga mereka tidak akan tahu apa yang aku rasakan",
    "Aku adalah orang yang selalu tegang dan serius",
    "Aku sering bekerja di bawah pimpinan orang yang tampaknya telah mengatur semuanya dengan baik, sehingga mereka mendapat pujian untuk hasil kerjanya, akan tetapi melimpahkan kesalahan kepada bawahannya",
    "Aku kadang-kadang sukar untuk mempertahankan hak-hakku, karena aku terlalu pendiam dan malu-malu",
    "Hal-hal yang kotor menakutkan atau memuakkan aku",
    "Aku mempunyai kehidupan alam khayalan yang tidak aku ceritakan kepada siapapun juga",
    "Beberapa anggota keluarga-ku mempunyai sifat mudah marah",
    "Aku tidak mampu melakukan sesuatu dengan baik",
    "Aku sering merasa berdosa, karena aku cenderung menganggap salah dari apa saja yang aku lakukan",
    "Aku selalu mempertahankan pendirian-ku dengan gigih",
    "Aku tidak takut pada laba-laba",
    "Masa depan-ku tampaknya suram",
    "Anggota keluarga-ku dan keluarga dekat-ku mempunyai hubungan baik sekali",
    "Aku ingin mengenakan pakaian yang mahal-mahal",
    "Orang-orang mudah sekali merubah pendirian-ku, meskipun aku telah mengambil keputusan",
    "Aku dibuat tegang dan gugup oleh binatang-binatang tertentu",
    "Aku tahan terhadap nyeri (sakit) seperti orang lain",
    "Acapkali aku termasuk orang yang terakhir yang menyerah dalam menghadapi suatu persoalan",
    "Aku menjadi marah bila orang-orang membuat aku terburu-buru",
    "Aku tidak takut pada tikus",
    "Beberapa kali dalam seminggu, aku merasa seolah-olah sesuatu yang menakutkan akan terjadi",
    "Aku sering sekali merasa lelah",
    "Aku suka memeriksa (mengecek) kunci pintu",
    "Kadang-kadang aku yakin bahwa orang-orang lain dapat mengetahui apa yang sedang aku pikirkan",
    "Aku suka membaca tentang ilmu pengetahuan",
    "Aku takut berada sendirian di tempat luas dan terbuka",
    "Aku kadang-kadang merasa seolah-olah diri-ku akan menjadi terpecah-pecah",
    "Banyak orang bersalah karena tingkah laku seks yang buruk",
    "Aku sering terbangun ketakutan di tengah malam",
    "Aku sering terganggu oleh sifat pelupa-ku meletakan barang-barang",
    "Orang yang paling dekat dan paling dipuja semasa kanak-ku adalah seorang wanita (ibu, kakak perempuan, bibi atau perempuan lainnya)",
    "Aku lebih suka kisah petualangan dari pada kisah cinta",
    "Aku sering menjadi bingung dan lupa apa yang ingin aku katakan",
    "Aku sangat lamban dan tidak gesit",
    "Aku suka sekali berolahraga yang keras (seperti sepak bola atau soccer)",
    "Aku benci seluruh keluarga-ku",
    "Sementara orang berpendapat bahwa sangat sukar mengenal diri-ku",
    "Aku menghabiskan sebagian besar waktu luangku dengan diri-ku sendiri",
    "Ketika orang melakukan sesuatu yang membuat aku marah, aku mengungkapkan kepada mereka bagaimana perasaan-ku tentang hal tersebut",
    "Aku biasanya sulit memutuskan apa yang harus aku lakukan",
    "Orang-orang tidak menganggap aku menarik",
    "Orang-orang tidak begitu ramah dan baik hati terhadap aku",
    "Aku sering merasa tidak sebaik seperti orang lain",
    "Aku sangat keras kepala (bebal)",
    "Aku senang mengisap ganja (marijuana)",
    "Gangguan jiwa adalah tanda dari kelemahan seseorang",
    "Aku mempunyai masalah dengan obat-obatan atau minuman beralkohol",
    "Roh atau makhluk halus dapat mempengaruhi orang untuk kebaikan atau keburukan",
    "Aku merasa tidak berdaya ketika aku harus membuat beberapa keputusan penting",
    "Aku selalu berusaha ramah termasuk ketika orang-orang sedang marah atau menghujat",
    "Ketika aku mempunyai masalah, aku merasa terbantu dengan membicarakannya bersama seseorang",
    "Tujuan utama dalam hidup-ku masih dalam jangkauan kemampuan-ku",
    "Aku yakin orang-orang harus menyimpan masalah-masalah pribadinya untuk mereka sendiri",
    "Aku tidak merasa banyak tekanan atau beban mental belakangan ini",
    "Aku sangat terganggu oleh pikiran tentang membuat perubahan dalam hidup-ku",
    "Masalah terbesar-ku disebabkan oleh tingkah laku seseorang yang dekat dengan aku",
    "Aku benci pergi ke dokter walaupun ketika aku sakit",
    "Meskipun aku tidak bahagia dengan hidup-ku, tidak ada yang dapat aku lakukan untuk itu sekarang ini",
    "Mengatasi masalah dan kecemasan melalui membicarakannya dengan seseorang, sering lebih menolong daripada melalui menggunakan obat-obatan",
    "Aku mempunyai beberapa kebiasaan yang benar-benar berbahaya",
    "Ketika menghadapi masalah yang perlu dipecahkan, aku biasanya membiarkan orang lain mengambil alih",
    "Aku menemukan beberapa kesalahan di dalam diri-ku yang tidak akan mampu aku rubah",
    "Aku sangat terganggu dengan apa yang harus aku lakukan setiap hari, sehingga aku ingin sekali bebas dari hal tersebut.",
    "Akhir-akhir ini, aku telah pikir-pikir untuk bunuh diri",
    "Aku sering menjadi mudah marah ketika orang mengganggu kelancaran pekerjaan-ku",
    "Aku sering merasa bisa membaca pikiran-pikiran orang lain",
    "Keharusan membuat keputusan penting membuat aku gelisah",
    "Orang-orang mengatakan bahwa aku makan terlalu banyak",
    "Aku mabok (minuman beralkohol) setiap minggu sekali atau lebih",
    "Aku telah mengalami kehilangan yang menyedihkan (tragis), yang aku tahu aku tidak akan pernah bisa mengembalikannya",
    "Kadang-kadang aku menjadi begitu marah dan tegang, yang aku tidak tahu apa penyebabnya",
    "Ketika orang meminta berbuat sesuatu, aku sulit mengatakan tidak",
    "Aku tidak pernah lebih bahagia dari pada ketika aku sendirian",
    "Hidupku kosong dan tidak ber-arti",
    "Aku menemukan kesulitan untuk bertahan pada suatu pekerjaan",
    "Aku telah berbuat banyak kesalahan yang buruk dalam hidup-ku",
    "Aku marah terhadap diri-ku sendiri yang terlalu banyak peduli dengan orang lain",
    "Akhir-akhir ini, aku banyak berpikir tentang bunuh diri",
    "Aku suka membuat keputusan dan memberi tugas kepada orang lain",
    "Walaupun tanpa keluarga-ku, aku tahu selalu ada seseorang yang akan mengurus aku",
    "Aku benci harus antri di bioskop, restoran, atau tontonan olahraga",
    "Walaupun tidak ada yang tahu, aku telah mencoba bunuh diri",
    "Semua-nya berlangsung terlalu cepat disekitar-ku",
    "Aku tahu aku menjadi beban buat orang lain",
    "Setelah seharian penuh masalah, aku biasanya butuh beberapa minuman beralkohol untuk rileks (santai)",
    "Kebanyakan kesulitan-ku disebabkan oleh nasib buruk",
    "Ada kalanya aku tidak bisa berhenti bicara",
    "Kadang-kadang aku melukai diri-ku sendiri tanpa sebab yang jelas",
    "Aku bekerja dalam jangka waktu yang panjang, walaupun pekerjaan-pekerjaan-ku tidak membutuhkan waktu sepanjang itu",
    "Aku biasanya merasa lebih lega setelah unek-unek-ku keluar",
    "Aku lupa dimana aku meletakkan barang-barang-ku",
    "Bila aku dapat hidup ulang kembali, aku tidak akan berubah banyak",
    "Aku menjadi sangat mudah marah bila orang yang aku harapkan tidak melaksanakan pekerjaannya tepat waktu",
    "Bila aku menjadi tegang, aku pasti mengalami sakit kepala",
    "Aku suka tawar-menawar yang alot",
    "Kebanyakan laki-laki tidak setia kepada istri-nya, pada waktu sekarang dan yang akan datang",
    "Akhir-akhir ini aku telah hilang semangat untuk mengatasi masalah-masalah-ku",
    "Bila aku minum minuman beralkohol, aku menjadi marah-marah dan memecahkan piring-gelas atau perabotan rumah tangga",
    "Aku bekerja sangat baik bila aku diberikan batas waktu yang pasti",
    "Aku menjadi sangat marah kepada seseorang yang aku rasakan seperti akan meledak-ledak",
    "Ada kalanya muncul pikiran-pikiran yang menakutkan tentang keluarga-ku",
    "Orang-orang mengatakan aku mempunyai masalah dengan minuman beralkohol, tetapi aku tidak setuju",
    "Aku selalu punya waktu yang terlalu sedikit untuk melaksanakan sesuatu",
    "Pikiran-ku akhir-akhir ini makin lebih cenderung ke soal kematian dan kehidupan di akhirat",
    "Aku sering menyimpan barang-barang yang mungkin tidak pernah aku gunakan",
    "Ada kalanya aku menjadi sangat marah, sehingga aku telah melukai seseorang dalam suatu perkelahian",
    "Apapun yang aku lakukan belakangan ini, aku merasa seperti sedang diuji",
    "Sekarang ini hanya sedikit yang dapat aku lakukan bersama dengan keluarga-ku",
    "Aku kadang-kadang mendengar pikiran-pikiran-ku berbicara keras",
    "Ketika aku sedih, kunjungan kawan-kawan-ku selalu dapat menghilangkannya",
    "Kebanyakan dari apa yang terjadi pada diri-ku ini tampaknya sudah pernah terjadi sebelumnya",
    "Ketika hidup-ku menjadi sulit, ini membuat aku ingin menyerah saja",
    "Aku tidak mampu berjalan masuk ke kamar yang gelap sendirian, walaupun masih dalam rumah sendiri",
    "Aku sangat mengkhawatirkan mengenai keuangan",
    "Laki-laki seharusnya menjadi kepala keluarga",
    "Tempat satu-satunya dimana aku merasa tenang adalah di dalam rumah sendiri",
    "Orang-orang yang bekerja dengan aku, tidak simpati dengan masalah-masalah-ku",
    "Aku puas dengan jumlah uang yang aku hasilkan",
    "Aku biasanya mempunyai tenaga yang cukup untuk melakukan pekerjaan-ku",
    "Sulit bagi-ku untuk menerima pujian-pujian",
    "Pada kebanyakan perkawinan, satu atau kedua pasangannya tidak bahagia",
    "Aku hampir tidak pernah lepas kendali diri",
    "Apa yang diberitahu orang kepada aku akhir-akhir ini, membutuhkan banyak usaha untuk mengingatnya",
    "Ketika aku sedih atau murung, pekerjaan-ku menjadi terlantar",
    "Kebanyakan pasangan perkawinan tidak banyak menunjukkan rasa kasih sayangnya satu kepada yang lain"
];

if ($_SERVER['REQUEST_METHOD'] !== 'POST' || ($_POST['confirm_seed'] ?? '') !== 'MMPI_SEED_CONFIRM') {
    ?>
    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Seed Questions Safety Lock</title>
        <style>
            body { font-family: Arial, sans-serif; background: #f8fafc; color: #0f172a; padding: 32px; }
            .card { max-width: 760px; margin: 0 auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 16px; padding: 24px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); }
            .danger { color: #b91c1c; }
            code { background: #f1f5f9; padding: 2px 6px; border-radius: 6px; }
            button { background: #b91c1c; color: #fff; border: 0; border-radius: 10px; padding: 12px 18px; cursor: pointer; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>Seed Questions Dikunci</h1>
            <p class="danger">Halaman ini sebelumnya menghapus isi <code>mmpi_questions</code> dan mengisi ulang hanya teks soal, sehingga kategori dan skala bisa reset.</p>
            <p>Untuk mencegah kerusakan data, halaman ini tidak akan mengeksekusi seeding saat dibuka biasa.</p>
            <p>Jika benar-benar ingin menjalankan seeding manual, kirim request <code>POST</code> dengan field <code>confirm_seed=MMPI_SEED_CONFIRM</code> setelah backup database dibuat.</p>
            <form method="post">
                <input type="hidden" name="confirm_seed" value="MMPI_SEED_CONFIRM">
                <button type="submit" onclick="return confirm('Ini akan menghapus dan mengisi ulang tabel mmpi_questions. Lanjut?')">Jalankan Seeding Manual</button>
            </form>
        </div>
    </body>
    </html>
    <?php
    return;
}

try {
    echo "<h3>Memulai proses seeding 567 Soal MMPI...</h3>";

    $db->exec("TRUNCATE TABLE mmpi_questions");
    echo "Tabel mmpi_questions dikosongkan...<br>";

    $stmt = $db->prepare("INSERT INTO mmpi_questions (question_number, question_text, category_id, is_active) VALUES (?, ?, 1, 1)");
    $successCount = 0;

    foreach ($questions as $index => $text) {
        $qNum = $index + 1;
        $textClean = trim($text);

        if ($stmt->execute([$qNum, $textClean])) {
            $successCount++;
        } else {
            echo "Gagal insert soal no $qNum<br>";
        }
    }

    echo "<hr>";
    echo "<strong>BERHASIL!</strong> $successCount soal telah dimasukkan ke database.<br>";
    echo "Jalankan pemulihan mapping setelah seeding jika diperlukan.";
} catch (PDOException $e) {
    echo "<strong>ERROR:</strong> " . $e->getMessage();
}
?>
